version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    target-branch: development
    schedule:
      interval: weekly
      time: "09:00"
    commit-message:
      prefix: build
      prefix-development: build
      include: scope