name: Lint and Audit

on:
  push:
    branches: [ "master", "development" ]
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Rust Toolchain
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.rustup/toolchains
        key: ${{ runner.os }}-rust-toolchain
        restore-keys: |
          ${{ runner.os }}-rust-toolchain

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache Cargo Binaries
      uses: actions/cache@v3
      with:
        path: ~/.cargo/bin
        key: cargo-binaries-${{ runner.os }}-v1
        restore-keys: |
          cargo-binaries-${{ runner.os }}-v1

    - name: Install Clippy and Audit
      run: |
        rustup component add clippy
        cargo install cargo-audit || echo "Cargo Audit is already installed"

    - name: Check Formatting
      run: cargo fmt -- --check

    - name: Run Clippy
      run: cargo clippy --verbose -- -D warnings

    - name: Run Audit
      run: cargo audit
