name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper release notes generation
          
      - name: Get Version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Generate Release Notes
        id: release_notes
        run: |
          # Get the previous tag
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 ${{ github.ref }}^ 2>/dev/null || echo "")
          
          # Prepare the release notes content
          if [ -z "$PREVIOUS_TAG" ]; then
            # If this is the first tag
            echo "NOTES<<EOF" >> $GITHUB_ENV
            echo "## What's New" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "First release!" >> $GITHUB_ENV
            git log --pretty=format:"* %s (%an)" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            # If there are previous tags
            echo "NOTES<<EOF" >> $GITHUB_ENV
            echo "## What's Changed" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "Changes since $PREVIOUS_TAG:" >> $GITHUB_ENV
            git log --pretty=format:"* %s (%an)" $PREVIOUS_TAG..${{ github.ref }} >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ env.NOTES }}
          draft: false
          prerelease: false

  build_and_upload:
    needs: create_release
    name: Build and Upload - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform_name: linux-x86_64
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            platform_name: linux-armv7
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            platform_name: linux-aarch64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            platform_name: win
          - os: macos-latest
            target: x86_64-apple-darwin
            platform_name: mac

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      # Modified cross-compilation tools installation for ARM targets
      - name: Install cross-compilation tools for ARMv7
        if: matrix.target == 'armv7-unknown-linux-gnueabihf'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf libc6-dev-armhf-cross
          echo 'CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc' >> $GITHUB_ENV

      # New step specifically for ARM64
      - name: Install cross-compilation tools for ARM64
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross
          echo 'CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc' >> $GITHUB_ENV

      # Set up cross build using the cross tool
      - name: Install cross
        if: contains(matrix.target, 'arm')
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      # Update Cargo.toml to use vendored OpenSSL
      - name: Configure vendored OpenSSL
        if: contains(matrix.target, 'arm')
        run: |
          # Add openssl-sys with vendored feature to the workspace dependencies
          # This is the simplest way to handle OpenSSL cross-compilation
          cat >> Cargo.toml << EOF
          
          [patch.crates-io]
          openssl-sys = { version = "0.9.106", features = ["vendored"] }
          EOF

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
        env:
          # Use cross for ARM targets
          CARGO_BUILD_TARGET: ${{ matrix.target }}
          CARGO_TERM_COLOR: always
          
      - name: Prepare binary for upload
        shell: bash
        run: |
          # Extract version without 'v' prefix
          VERSION=${{ needs.create_release.outputs.version }}
          VERSION_NUMBER=${VERSION#v}
          
          # Set the asset name with the requested format
          if [[ "${{ matrix.platform_name }}" == "win" ]]; then
            ASSET_NAME="reccedns-${VERSION}-${{ matrix.platform_name }}.exe"
          else
            ASSET_NAME="reccedns-${VERSION}-${{ matrix.platform_name }}"
          fi
          echo "ASSET_NAME=${ASSET_NAME}" >> $GITHUB_ENV
          
          # Copy the binary with proper naming
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            # For Windows, copy the executable directly
            cp target/${{ matrix.target }}/release/reccedns.exe ${ASSET_NAME}
          else
            # For Linux and macOS, find the executable and copy it
            mkdir -p dist
            cp target/${{ matrix.target }}/release/reccedns dist/ 2>/dev/null || cp target/${{ matrix.target }}/release/reccedns* dist/
            cd dist
            # Find the main executable (assumed to be named 'reccedns')
            cp reccedns ../${ASSET_NAME} 2>/dev/null || cp $(find . -type f -perm -u=x | head -1) ../${ASSET_NAME}
            cd ..
          fi

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ env.ASSET_NAME }}
          asset_name: ${{ env.ASSET_NAME }}
          asset_content_type: application/octet-stream